sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
#  - flake8 environment.py
  - cp config/uat.cfg.sample config/uat.cfg
script: 
  - behave --dry-run features/rhelah/
  - behave --dry-run features/atomic/
